---
name: rolling build
on:
- workflow_dispatch
- push

concurrency:
  group: rolling-build
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:
    - name: setup deno
      uses: denoland/setup-deno@0df5d9c641efdff149993c321fc27c11c5df8623 # v1.1.3
    - name: install system dependencies
      run: sudo apt-get update && sudo apt-get install oxipng

    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: run fetch zips
      run: chmod +x scripts/fetchZips.sh; ./scripts/fetchZips.sh

    - name: (temporary) upload zips dir as artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        path: assets/zips
